### PR TITLE
New Operations related to String Algebras

### PR DESCRIPTION
**Pull request by BhargavKK**
Hello,
I (BhargavKK) and Amit Kuber (expinfinity) have been working on new operations related to string algebras for past few months. I have added some of its codes in this pull request. I have also added relevant documentation in the 'doc' folder in the 'Path Algebras' chapter, section 4.12. The ideas and concepts used in the codes have been inspired from this paper - https://arxiv.org/pdf/2008.06005.pdf

We are looking forward to comments and suggestions for improvement.

### CODE REVIEW

**Comment by sunnyquiver** [comment]
First of all, thank you very much for the contribution to QPA!  I have wanted to get time to understand the code, but I have never gotten to it.  So I hope that you have time to answer some (probably stupid) questions?  When I read the documentation, it says somewhere that one is limited to 26 arrows.  How is this limitation used, and why is it important?

**Comment by BhargavKK** [comment]
1 Yes, you are absolutely right. I have made the necessary changes in "validity.gi" and "stringalgebra.gi" and replaced "Incoming_Arrows" and "Outgoing_Arrows" with existing attribute "IncomingArrowsOfVertex" and "OutgoingArrowsOfVertex".
2. For the operations "IsValidString", "IsABand" and "IsDomesticStringAlgebra", we have outputs more than "true" or "false" due to some outliers cases. For e.g. if the presentation (Q, \rho) is not a string algebra or for the operation "IsABand", if the "input_str" is not a Valid String, then we thought, for such cases output should be something more than just "false". Nevertheless, we can always go back to just returning "true" or "false".
3. Initially we tried using only Quiver Algebra as one argument for "IsDomesticStringAlgebra". Although it was possible to extract the quiver from that quiver algebra using "QuiverOfPathAlgebra", we couldn't separate "\rho" (relations) from it.

**Comment by BhargavKK** [comment]
Changes made in the code

1. Defined global functions "QPAStringQuiverRho", "QPAStringSigmaEps", "QPAStringDirectLeft", "QPAStringInverseLeft", "QPAStringDirectRight" and "QPAStringInverseRight" in "validity.gi".
2. Have passed appropriate error messages at appropriate places in "validity.gi" and "stringalgebra.gi", The operations "IsValidString", "IsABand" and "IsDomesticStringAlgebra" returns only "true" or "false". All other previous output conditions have been changed to error messages.
3. The problem actually arises after using "RelationsOfAlgebra (A)". For e.g. 
Capture
We are unable to convert relations into words (["bc", "cd"] in this case).
4. Regarding general arguments like "IsList" and "IsString", we have taken care of all the cases which could give erratic outputs. For e.g. If the "input_str" in "IsValidString" contains an unacceptable character, then it returns "false" itself. We have also added a category "IsQuiverSA" (name can be changed). The quivers in this category are in accordance with the conditions mentioned in [above comment](https://github.com/gap-packages/qpa/pull/58#issuecomment-939834992) or in the report. We have defined it in "quiver.gi"

**Comment by sunnyquiver** [comment]
3. Here is one way of dealing with this problem:  
```
gap> rels := RelationsOfAlgebra(A);                    
[ (1)*c^2, (1)*d*e, (1)*e*a, (-1)*b*d+(1)*a*c*d, (1)*e*b*d ]
gap> rels[4];
(-1)*b*d+(1)*a*c*d
gap> onerel := CoefficientsAndMagmaElements( rels[4] );
[ b*d, -1, a*c*d, 1 ]
gap> pathonerel := WalkOfPath( onerel[1] );            
[ b, d ]
gap> string := List( pathonerel, a -> String( a ) );
[ "b", "d" ]
gap> Concatenation( string );
"bd"
```
Will this help you?

**Functions defined multiple times:** 
Having functions that are defined multiple times makes the code harder to maintain and less transparent.  So one should avoid lengthy functions defined multiple times. Furthermore, if a function is defined multiple times, it might indicate that the function is of independent interest and it might occur in future developments/extensions.  Therefore, as soon as a function is defined multiple times, it should be defined as a global function.  For example, I still see that computeLPSarray, SourceOfArrow, TargetOfArrow, CyclicPermutationOfBand, NumberOfJoints, and MaximumLengthOFDirectString are multiply defined.  Are there others? Furthermore, what is the relationship between SourceOfArrow and SourceOfPath, and TargetOfArrow and TargetOfPath? The function MaximumLengthOFDirectString breaks the "name convention" by using OF and not Of.  Accident or on purpose? 

If one defines a function within an operation/function, ask yourself if this function is of interest in its own right and deserve to be define as such.  Examples here are WeakBridgeQuiver, BandFreeStrings, IsBandFreeString. 

Again, thank you very much for all your efforts.

**Comment by BhargavKK** [comment]
The problem I was dealing with Relations has been solved with the help of your suggestion. Thanks a lot!

1. Have made all the functions defined multiple times as global functions.
2. Changed the name of "MaximumLengthOFDirectString" to "MaximumLengthOfDirectString". I don't know how that happened.
3. I have also changed the arguments of all the functions. I have replaced "Q" (quiver) and "rho" (set of monomial relations) with "A" (an algebra). The code returns error message if "A" is not a string algbera, else continues as usual.
3. While defining the method "BridgeQuiver", the function "IsBandFreeString" is used in the function "BandFreeStrings" to find all the band free strings and in "BridgeQuiver1" function. So I think this function has to be defined explicitly. Other 3 functions in this method, which are "BandFreeStrings", "WeakBridgeQuiver" and "BridgeQuiver1" are defined in order to simplify the structure of code while examining it. It will probably be easier to understand the algorithm. I can remove "WeakBridgeQuiver" and "BridgeQuiver1" functions, but "IsBandFreeString" and "BandFreeStrings" are necessary, I think.

**Comment by sunnyquiver** [comment]
Thank you again for all your efforts!

I hope that you can see the report above under the heading "Some checks were not successful".  I think that the tests for your contribution needs to be updated to match the modified code.  Otherwise the code looks good to me now.  In comparison, the first version was approximately 3200 lines, while the latest version is approximately 2150 lines.  So if you can change the tests for the code, so that it will pass the checks by GAP, I will then merge your contribution into the master.

**Comment by BhargavKK** [comment]
Added the test cases

**Comment by sunnyquiver** [comment]
All checks passed.  Merge with master done. 

Thank you very much for your contribution!

**Pull request merged**
